//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package io.openvidu.server.stt.grpc;

import io.grpc.ManagedChannel;
import io.openvidu.server.pro.stt.grpc.autogenerated.SpeechToTextGrpc;

public class GrpcChannel {
    public ManagedChannel channel;
    public SpeechToTextGrpc.SpeechToTextStub sttServiceBlockingStub;
    public SpeechToTextGrpc.SpeechToTextFutureStub sttServiceFutureBlockingStub;

    public GrpcChannel() {
    }
}
